In [6]:
import numpy as np
datafile = np.genfromtxt('data.txt',delimiter=',')
datafile.astype(int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [ ]:
#boolean masking and advancing indexing
datafile > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [9]:
datafile[datafile>39]

array([40.])

In [ ]:
#we can index a list using numpy 
a = np.array([1,2,3,4,5,6,7,8])
a[[7]]

array([8])

In [23]:
np.any((datafile > 30) & (datafile <40))

np.True_

In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],
         [26,27,28,29,30]])

print(a)
print(a[[0,4,5],3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ 4  5]
 [24 25]
 [29 30]]
