In [4]:
#initializing different types of arrays
import numpy as np


In [5]:
a = np.ones((5,3,3))

In [6]:
np.full((3,2),23)

array([[23, 23],
       [23, 23],
       [23, 23]])

In [7]:
np.full_like(a,5) #it changes the already existing array by specifing that 

array([[[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]])

In [11]:
np.random.rand(5,5)

array([[0.68685503, 0.44618771, 0.22383459, 0.19065114, 0.35356019],
       [0.71100646, 0.30317401, 0.36574061, 0.59073355, 0.86425069],
       [0.70058077, 0.1534167 , 0.46298808, 0.97856061, 0.43830542],
       [0.67044151, 0.99803758, 0.84416101, 0.86597705, 0.39541131],
       [0.66993047, 0.50487235, 0.35939867, 0.99967295, 0.17147998]])

In [12]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.random.random_sample(a.shape)

array([[0.18272604, 0.80317506, 0.68293318],
       [0.68821972, 0.38349001, 0.15536876],
       [0.31003351, 0.50052242, 0.52807604]])

In [17]:
#random integer values
np.random.randint(0,2,size= a.shape)

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 0]])

In [20]:
#identitity matrix 
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
b = np.array([[[1,2,3],[4,5,6]]])

repeat = np.repeat(b,5,axis=0)

print(repeat)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [40]:
a= np.ones((5,5))
b = np.zeros((3,3))
b[1,1] = 9
a[1:4,1:4] = b

print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [42]:
#be careful when coping arrays in python

m = np.array([1,2,3])
n = m.copy()
n[0] = 100
print(m)
print(n)

[1 2 3]
[100   2   3]
