In [25]:
# Linear Algebra
import numpy as np

a = np.ones((2,3))
b = np.full((3,2), 2)

In [26]:
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [27]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [30]:
c = np.identity(3)

print(c)

d = np.linalg.det(c)

print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0
