In [1]:
import numpy as np
a = np.array([1,2,3,4,5])

In [3]:
b = a + 2
print(b)

[3 4 5 6 7]


In [4]:
a - 2

array([-1,  0,  1,  2,  3])

In [5]:
a * 2

array([ 2,  4,  6,  8, 10])

In [6]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [7]:
a//2

array([0, 1, 1, 2, 2])

In [10]:
b = np.array([3,4,5,6,7])

a + b

array([ 4,  6,  8, 10, 12])

In [11]:
a ** b

array([    1,    16,   243,  4096, 78125])

In [12]:
#sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [14]:
np.asin(a)

/var/folders/0h/030y6v9930zgbltrby15sc480000gn/T/ipykernel_10873/390350937.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.asin(a)


array([1.57079633,        nan,        nan,        nan,        nan])