In [ ]:
import numpy as np

a = np.array([1,2,3],dtype= int)
print(a)

[1 2 3]


In [25]:
b = np.array([[1,2.3,4.5,6.0],[2.3,4.5,6.0,3.4]],dtype=float)
print(b)

[[1.  2.3 4.5 6. ]
 [2.3 4.5 6.  3.4]]


In [26]:
b.ndim
a.ndim

1

In [27]:
b.shape

(2, 4)

In [29]:
b.dtype

dtype('float64')

In [33]:
a.itemsize

8

In [36]:
c = np.array([['sai','teja','chowdary'],['mark','xmen','analaysis']],dtype=str)

c.size

6

In [39]:
totalsize = c.size * c.itemsize

print(totalsize)

216


In [41]:
totalsize_a= a.itemsize * a.size

print(totalsize_a)

24


In [43]:
c.nbytes
a.nbytes

24

In [44]:
b.nbytes

64

In [46]:
new_array = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

print(new_array)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [48]:
new_array.shape

(2, 7)

In [52]:
print(new_array[1,4])

12


In [ ]:
print(new_array[0])#for the specific row

[1 2 3 4 5 6 7]


In [ ]:
print(new_array[:,5])# for the specific column


[ 6 13]


In [75]:
new_array[1, 1:6:2] #slicing [array_index, startindex:endindex:stepindex]

array([ 9, 11, 13])

In [76]:
b[0, 1:4:2]

array([2.3, 6. ])

In [77]:
new_array2 = np.array([[10,20,30,40,50],[60,70,80,90,100],[110,120,130,140,150]])
new_array2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [81]:
new_array2[2,1] = 120
print(new_array2)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [120 120 130 140 150]]


In [82]:
new_array2[:, 2] = 230
print(new_array2)

[[ 10  20 230  40  50]
 [ 60  70 230  90 100]
 [120 120 230 140 150]]


In [83]:
new_array2[:, 3]= [4,9,14]
print(new_array2)

[[ 10  20 230   4  50]
 [ 60  70 230   9 100]
 [120 120 230  14 150]]


In [85]:
new_array3 = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],[[10,20,30,40,50],[60,70,80,90,100],[110,120,130,140,150]]])

print(new_array3)

[[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [ 11  12  13  14  15]]

 [[ 10  20  30  40  50]
  [ 60  70  80  90 100]
  [110 120 130 140 150]]]


In [87]:
print(new_array3[0,1,0])

6


In [101]:
new_array3[:,:,4]=[[5,5,5],[5,5,5]]
print(new_array3)

[[[  1   2   3   4   5]
  [  6   7   8   9   5]
  [ 11  12  13  14   5]]

 [[ 10  20  30  40   5]
  [ 60  70  80  90   5]
  [110 120 130 140   5]]]
