In [9]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(np.min(a))
print(np.max(a,axis=0))


1
[7 8 9]


In [15]:
print(np.sum(a))

45


In [21]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

ab = b.reshape((3,3))
print(ab)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
#vertical stacking
i = np.array([1,2,3])
j = np.array([4,5,6])

np.vstack(i)
np.vstack([i,j,j,i,j,i])

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [29]:
np.hstack([i,j,j,i])

array([1, 2, 3, 4, 5, 6, 4, 5, 6, 1, 2, 3])